In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
file="C:/Users/oddoy/Documents/Jupyter Notebooks/ny-city-owned-and-leased-property/city-owned-and-leased-property-local-law-48-of-2011.csv"

In [4]:
owned_leased=pd.read_csv(file)
owned_leased.head()

C:\Users\oddoy\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (20,65) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Date Created,Borough,Map Atlas,Block,Lot,Address,Parcel Name,Agency,Current Uses,Total Area,...,SP Dist 1,SP Dist 2,Potential Urban Ag,Contact,EDC % Occupied,Pluto Version,Latitude,Longitude,BIN,NTA
0,2013-12-11T00:00:00,1,4.0,2,1,MARGINAL STREET,BATTERY MARITIME BLDG / FERRY,"DOT, DSBS","FERRY TERMINAL, WATERFRONT PROPERTY, NO USE",209215,...,LM,NaN,NaN,Christian Grove cgrove@dcas.nyc.gov 212 386-0613,0.0,13v1,NaN,NaN,NaN,NaN
1,2013-12-11T00:00:00,1,4.0,2,23,PIER 6,PIER 6,DSBS,"NO USE, FINAL COMMITMNT-DISP, IN USE-TENANTED,...",510025,...,LM,NaN,NaN,Christian Grove cgrove@dcas.nyc.gov 212 386-0613,0.0,13v1,40.701481,-74.009171,1075697.0,Battery Park City-Lower Manhattan ...
2,2013-12-11T00:00:00,1,4.0,3,1,BATTERY PARK,BATTERY PARK,PARKS,PARK,945425,...,NaN,NaN,NaN,Christian Grove cgrove@dcas.nyc.gov 212 386-0613,0.0,13v1,40.702880,-74.015523,1000000.0,park-cemetery-etc-Manhattan ...
3,2013-12-11T00:00:00,1,4.0,3,2,PETER MINUIT PLAZA,PETER MINUIT PLAZA/BATTERY PK,PARKS,PARK,39900,...,NaN,NaN,NaN,Christian Grove cgrove@dcas.nyc.gov 212 386-0613,0.0,13v1,40.702153,-74.013146,1085598.0,Battery Park City-Lower Manhattan ...
4,2013-12-11T00:00:00,1,4.0,3,3,PETER MINUIT PLAZA,PETER MINUIT PLAZA/BATTERY PK,PARKS,PARK,33600,...,NaN,NaN,NaN,Christian Grove cgrove@dcas.nyc.gov 212 386-0613,0.0,13v1,40.702153,-74.013146,1085598.0,Battery Park City-Lower Manhattan ...